name: Pennyful
favicon: null
layout_spectrum: 0.50751
typography_spectrum: 0.89316
title: "India's #1 Cash Back and Coupons Site"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a6eb9'
    - '#ffffff'
    - '#000000'
    - '#609acb'
    - '#686868'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
